# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('title', models.TextField()),
                ('place', models.TextField()),
                ('type', models.TextField(choices=[('essential', 'Essential'), ('food', 'Food'), ('events', 'Events'), ('talks', 'Talks')])),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('begin',),
            },
        ),
    ]
